### ISSUE TITLE
Test broke on windows

### ISSUE THREAD

**Issue by at15** [arrowrowe/tam#11]
- node 6.3.1
- git bash 
- windows 10

The error stack is following 

````
No coverage information was collected, exit without writing coverage information
E:\workspace\src\github.com\arrowrowe\tam\node_modules\.bin\_mocha.cmd:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Object.Module._extensions.(anonymous function) [as .js] (E:\workspace\src\github.com\arrowrowe\tam\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at runFn (E:\workspace\src\github.com\arrowrowe\tam\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    at E:\workspace\src\github.com\arrowrowe\tam\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
 npm ERR! Test failed.  See above for more details.

````

related to https://github.com/gotwarlost/istanbul#usage-on-windows

**Comment by at15** [comment]
also using `istanbul cover _mocha 'test/**/*-spec.js'` with the `'`, I got `Error: cannot resolve path (or pattern) ''./test/**/*-spec.js''` after modify `_mocha` to the real path of js file, remove the quote and everything is working

**Comment by at15** [comment]
I guess mie has abandoned tam /w\

**Comment by arrowrowe** [comment]
no, i have abandoned windows

**Comment by arrowrowe** [comment]
also it seems a testsuit problem...... not interested (at least not now)

**Comment by at15** [comment]
@arrowrowe simple change in `package.json` will work, lazy mie

**Comment by arrowrowe** [comment]
(
