### ISSUE TITLE
Build fails on Windows due to different subpath slashes

### ISSUE THREAD

**Issue by ComMouse** [arrowrowe/tam#12]
The error output is as follows:

```
Error: Output [D:\Web\xxxx\yyyy\dist\jquery\jquery.min-8258d046.js] out of www [D:\Web\xxxx\yyyy/]!
    at D:\Web\xxxx\yyyy\node_modules\tam\lib\link.js:14:13
    at Array.map (native)
    at getOutput (D:\Web\xxxx\yyyy\node_modules\tam\lib\link.js:11:6)
    at D:\Web\xxxx\yyyy\node_modules\tam\lib\link.js:34:18
    at fr (D:\Web\xxxx\yyyy\node_modules\tam\lib\link.js:26:7)
    at Object.module.exports [as link] (D:\Web\xxxx\yyyy\node_modules\tam\lib\link.js:33:3)
    at Object.module.exports [as run] (D:\Web\xxxx\yyyy\node_modules\tam\lib\cli\run.js:41:21)
    at Gulp.<anonymous> (D:\Web\xxxx\yyyy\gulpfile.js:15:7)
    at module.exports (D:\Web\xxxx\yyyy\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\Web\xxxx\yyyy\node_modules\orchestrator\index.js:273:3)
```

Need to handle both `\` and `/` when checking subdirectory...

@arrowrowe

**Comment by ComMouse** [comment]
A temporary workaround is to revise `lib/link.js`:

```javascript
if (file.replace(/\\/g, '/').substr(0, www.length) !== www.replace(/\\/g, '/')) {
  throw new Error('Output [' + file + '] out of www [' + www + ']!');
}
```

**Comment by arrowrowe** [comment]
solution should be in `lib/link.js` but here:

```javascript
www = path.resolve(www) + (www.substr(-1) === path.sep ? path.sep : '');
```
