### ISSUE TITLE
TypeError: path must be a string

### ISSUE THREAD

**Issue by at15** [arrowrowe/tam#5]
````
[16:32:12] Using gulpfile ~/repos/github.com/at15/MissAtomicBomb/gulpfile.js
[16:32:12] Starting 'build'...
[2015-10-12 16:32:12.172] [INFO] tam - tam @ 0.3.4 { assets: 'assets.json',
  mode: undefined,
  hash: undefined,
  log: 'info',
  help: false,
  version: false }
[2015-10-12 16:32:12.199] [INFO] tam - Package [font-awesome] begins building...
[2015-10-12 16:32:12.204] [INFO] tam - Package [font-awesome] built.
[16:32:12] 'build' errored after 34 ms
[16:32:12] TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at Object.module.exports [as run] (/Users/gpl/repos/github.com/at15/MissAtomicBomb/node_modules/tam/lib/cli/run.js:42:6)
    at Gulp.<anonymous> (/Users/gpl/repos/github.com/at15/MissAtomicBomb/gulpfile.js:15:9)
    at module.exports (/Users/gpl/repos/github.com/at15/MissAtomicBomb/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/gpl/repos/github.com/at15/MissAtomicBomb/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/gpl/repos/github.com/at15/MissAtomicBomb/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/gpl/repos/github.com/at15/MissAtomicBomb/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/gpl/.nvm/versions/node/v0.12.7/lib/node_modules/gulp/bin/gulp.js:129:20
````

see this commit https://github.com/at15/MissAtomicBomb/commit/40cd51cecf9612dde68aff11847c8f25e24558af
though the files are copied properly.

**Comment by arrowrowe** [comment]
I will look into this.

**Comment by arrowrowe** [comment]
Fixed in 08f0185d62f4c165caa26b1de7ffc15be2e10e87.

```
[2015-10-13 17:50:48.978] [INFO] tam - tam @ 0.3.5 { assets: 'assets.json',
  log: 'info',
  help: false,
  version: false,
  mode: undefined,
  hash: undefined }
[2015-10-13 17:50:48.988] [INFO] tam - Package [font-awesome] begins building...
[2015-10-13 17:50:48.991] [INFO] tam - Package [font-awesome] built.
[2015-10-13 17:50:48.991] [WARN] tam - No `linked` found in [assets.json]. Linked's output fails.
```

**Comment by at15** [comment]
@arrowrowe I will have a try later

**Comment by arrowrowe** [comment]
After commit ed073bda9dcd8bd0d107b4662cca23e79c8b7423, Tam has a default value `'linked.json'` for `assets.linked`, providing a warning as well.
